# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fa8f98fcf06a6f509525a6623c7d67e5262b0ff5cab0c083ffdb2e83e54a046e037d933fa38b0d0815b83ab7ee291fcd4296383eefce5612b5b9b7e259137f4

test:
  secret_key_base: 03f26fae7e94b225ae8d46b3a44fe5cc02cac69cf67e08399b1037af8f919be71bf881a32adbccbdcbfd404a8d891da839d7ee336b30f96c30f439849f8b1aa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
